---
engines:
  tslint:
    channel: beta
    config: tslint.json
    enabled: true
exclude_patterns:
  - "config"
  - "**/*.d.ts"
  - "src/**/*.spec.ts"
  - "examples"
ratings:
  paths:
    - "src/**/*.ts"
